import type { Metadata } from "next";
import "./globals.css";

import { Geist, Geist_Mono } from "next/font/google";

import { ThemeProvider } from "@/components/providers/theme-provider";
import { Navbar } from "@/components/shared/navbar";
import { AnchoredToastProvider, ToastProvider } from "@/components/ui/toast";

const fontSans = Geist({ variable: "--font-sans", subsets: ["latin"] });
const fontHeading = Geist({
	variable: "--font-heading",
	subsets: ["latin"],
	weight: "600",
});
const fontMono = Geist_Mono({ variable: "--font-mono", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${fontSans.variable} ${fontHeading.variable} ${fontMono.variable} relative bg-sidebar font-sans text-foreground antialiased`}
			>
				<ThemeProvider>
					<ToastProvider>
						<AnchoredToastProvider>
							<div className="relative isolate flex min-h-svh flex-col overflow-clip [--header-height:4rem]">
								<div
									aria-hidden="true"
									className="container pointer-events-none absolute inset-0 z-45 before:absolute before:inset-y-0 before:-left-3 before:w-px before:bg-border/64 after:absolute after:inset-y-0 after:-right-3 after:w-px after:bg-border/64"
								/>
								<div
									aria-hidden="true"
									className="container pointer-events-none fixed inset-0 z-45 before:absolute before:top-[calc(var(--header-height)-4.5px)] before:-left-[11.5px] before:z-1 before:-ml-1 before:size-2 before:rounded-[2px] before:border before:border-border before:bg-popover before:bg-clip-padding before:shadow-xs/5 after:absolute after:top-[calc(var(--header-height)-4.5px)] after:-right-[11.5px] after:z-1 after:-mr-1 after:size-2 after:rounded-[2px] after:border after:border-border after:bg-background after:bg-clip-padding after:shadow-xs/5 dark:after:bg-clip-border dark:before:bg-clip-border"
								/>
								<Navbar />
								{children}
							</div>
						</AnchoredToastProvider>
					</ToastProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
